Revert "fix 3c515.c:(.text+0x57200): undefined reference to `pnp_get_resource'"
This reverts commit 109d4c4df6f273b1d7354422a869eb751ac6d296.

another fix is already upstream.