werror: fix warning in drivers/misc/fujitsu-laptop.c
this warning:

  drivers/misc/fujitsu-laptop.c:1119: warning: ‘pnp_ids’ defined but not used

triggers because the module device table is indeed unused when
building it into the kernel.

Annotate it.

Signed-off-by: Ingo Molnar <mingo@elte.hu>