vfs: turn vfs_lock_file() from macro into inline, on !FILE_LOCKING
this warning:

  fs/lockd/svclock.c: In function ‘nlmsvc_grant_blocked’:
  fs/lockd/svclock.c:719: warning: unused variable ‘file’
  fs/nfsd/nfs4state.c: In function ‘nfs4_open_delegation’:
  fs/nfsd/nfs4state.c:1626: error: unused variable ‘flp’

trigger because in the !FILE_LOCKING case the vfs_lock_file()
function (which makes use of the 'file' variable) is a macro,
so the preprocessor keeps the compiler from knowing that the
variable is indeed used.

Convert it to an inline instead.

Signed-off-by: Ingo Molnar <mingo@elte.hu>