drivers/media/video/cx231xx: disable due to build failure
drivers/built-in.o: In function `cx231xx_audio_fini':
cx231xx-audio.c:(.text+0xd4e43): undefined reference to `snd_card_free'
drivers/built-in.o: In function `cx231xx_audio_isocirq':
cx231xx-audio.c:(.text+0xd4fb7): undefined reference to `snd_pcm_link_rwlock'
cx231xx-audio.c:(.text+0xd5021): undefined reference to `snd_pcm_link_rwlock'
cx231xx-audio.c:(.text+0xd50bb): undefined reference to `snd_pcm_period_elapsed'
drivers/built-in.o: In function `snd_cx231xx_capture_open':