dvb: input layer dependencies fixes
testing of the -tip tree found the following build failures:

 drivers/built-in.o: In function `ttusb_dec_disconnect':
 ttusb_dec.c:(.text+0xa2c95): undefined reference to `input_unregister_device'

 drivers/built-in.o: In function `dvb_usb_read_remote_control':
 dvb-usb-remote.c:(.text+0xa6a94): undefined reference to `input_event'

with this config:

  http://redhat.com/~mingo/misc/config-Tue_May_20_03_48_57_CEST_2008.bad

these are due to the media/dvb layer having dependencies on INPUT
functionality, without having that spelled out in the Kconfig file.

this patch makes that dependency explicit, which solves the build error.

Signed-off-by: Ingo Molnar <mingo@elte.hu>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>