mtd/lpddr/qinfo_probe.c needs lpddr_cmds to be compiled
Alexander Beregalov wrote:
> drivers/built-in.o: In function `lpddr_probe':
> drivers/mtd/lpddr/qinfo_probe.c:215:
> undefined reference to `lpddr_cmdset'
>
> # CONFIG_MTD_LPDDR is not set
> CONFIG_MTD_QINFO_PROBE=y
> --

This patch has been posted, just needs to be merged (hint):
Signed-off-by: Ingo Molnar <mingo@elte.hu>