drm: sis depends on FB_SIS
cc: airlied@linux.ie

drm/sis calls mm functions in fb/sis, so make the former depend
on the latter.

This one happened with FB_SIS=m, AGP_SIS=y, DRM_SYS=y.

sis1.out:sis_mm.c:(.text+0x70014): undefined reference to `sis_free'
sis1.out:sis_mm.c:(.text+0x7002a): undefined reference to `sis_malloc'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Cc: airlied@linux.ie
Cc: akpm <akpm@linux-foundation.org>
Signed-off-by: Ingo Molnar <mingo@elte.hu>