kmemcheck: disable CPA self-test
CPA tests the present bit of ptes -- a recipe for disaster when
kmemcheck is used. It somehow results in our PTEs becoming
inaccessible:

ERROR: kmemcheck: Fatal error

Pid: 1, comm: swapper Tainted: G        W  2.6.29-rc6-00892-g9b7ff38-dirty #342 945P-A
RIP: 0010:[<ffffffff8023998b>]  [<ffffffff8023998b>] kmemcheck_pte_lookup+0x3b/0x50
RSP: 0018:ffff88003f87f788  EFLAGS: 00010046
RAX: ffffc00000000fff RBX: ffffffff81577f2d RCX: 00003ffffffff000
RDX: ffff88003d9b7bb8 RSI: 0000000000000000 RDI: 000000003d9b7063
RBP: ffff88003f87f798 R08: 00000000000000a5 R09: 0000000000000000
R10: ffff88003d9981c0 R11: 0000000000000010 R12: ffffffff802ce7ac
R13: ffffffff81577000 R14: 0000000000000004 R15: ffff88003f87f8d8
FS:  0000000000000000(0000) GS:ffff880002701000(0000) knlGS:0000000000000000
CS:  0010 DS: 0018 ES: 0018 CR0: 000000008005003b
CR2: ffff88003f804d60 CR3: 0000000000201000 CR4: 00000000000006a0
DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
DR3: 0000000000000000 DR6: 00000000ffff4ff0 DR7: 0000000000000400
 [<ffffffff8023817a>] kmemcheck_error_save_bug+0xba/0x100
 [<ffffffff80239301>] kmemcheck_access+0xd1/0x4a0
 [<ffffffff8023975d>] kmemcheck_fault+0x8d/0x90
 [<ffffffff80231f24>] do_page_fault+0x2b4/0x450
 [<ffffffff8103a075>] page_fault+0x25/0x30
 [<ffffffff80239aa8>] kmemcheck_shadow_lookup+0x28/0x60
 [<ffffffff8023941e>] kmemcheck_access+0x1ee/0x4a0
 [<ffffffff8023973a>] kmemcheck_fault+0x6a/0x90
 [<ffffffff80231f24>] do_page_fault+0x2b4/0x450
 [<ffffffff8103a075>] page_fault+0x25/0x30
 [<ffffffff80351efc>] sysfs_new_dirent+0x10c/0x120

Will need some more time to figure out this one. This is a temporary
fix until we can figure out how to make CPA self-test and kmemcheck
compatible.

Signed-off-by: Vegard Nossum <vegard.nossum@gmail.com>