fix build error in drivers/media/video/cx23885/cx23885-dvb.c
-tip testing found the following module build failure on latest -git:

    Building modules, stage 2.
    MODPOST 421 modules
    ERROR: "dib7000p_attach" [drivers/media/video/cx23885/cx23885.ko] undefined!
    make[1]: *** [__modpost] Error 1
    make: *** [modules] Error 2

with the following config:

    http://redhat.com/~mingo/misc/config-Tue_May_20_17_13_32_CEST_2008.bad

the problem is caused that ./drivers/media/video/cx23885/cx23885-dvb.c
depends on a DVB_DIB7000P symbol (dib7000p_attach), but its Kconfig rule
only selects it if DVB_FE_CUSTOMISE is enabled:

       select DVB_DIB7000P if !DVB_FE_CUSTOMISE

the minimal fix found is to select the DVB frontend driver unconditionally.

Signed-off-by: Ingo Molnar <mingo@elte.hu>