serial: work around broken istallion build
work around:

drivers/char/istallion.c:829: error: ‘struct stliport' has no member named ‘refcount'
drivers/char/istallion.c: In function ‘stli_close':
drivers/char/istallion.c:891: error: ‘struct stliport' has no member named ‘refcount'
[...]

a352def21a642133758b868c71bee12ab34ad5c5 is first bad commit
commit a352def21a642133758b868c71bee12ab34ad5c5
Author: Alan Cox <alan@redhat.com>
Date:   Wed Jul 16 21:53:12 2008 +0100

    tty: Ldisc revamp

Signed-off-by: Ingo Molnar <mingo@elte.hu>