8390: Fix ne.c build
Since commit 055e5110ae0c0c1176a75b78d789294f2ff2f7af ("8390: Split
8390 support into a pausing and a non pausing driver core"), ne.c
cause this build failure:

drivers/built-in.o: In function `ne_probe1':
ne.c:(.init.text+0x2464): undefined reference to `NS8390_init'
drivers/built-in.o: In function `ne_block_output':
ne.c:(.text.ne_block_output+0x1b0): undefined reference to `NS8390_init'

Signed-off-by: Atsushi Nemoto <anemo@mba.ocn.ne.jp>
Cc: jgarzik@redhat.com
Cc: akpm@linux-foundation.org
Cc: Alan Cox <alan@lxorguk.ukuu.org.uk>
Signed-off-by: Ingo Molnar <mingo@elte.hu>