watchdog: Fix build with CONFIG_ITCO_VENDOR_SUPPORT=n
Kernel 2.6.27-rc2-git2 fails to build with
CONFIG_ITCO_VENDOR_SUPPORT=n:

  CC [M]  drivers/watchdog/iTCO_vendor_support.o
drivers/watchdog/iTCO_vendor_support.c:247: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:249: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:255: error: 'iTCO_vendor_pre_start' undeclared here (not in a function)
drivers/watchdog/iTCO_vendor_support.c:255: warning: type defaults to 'int' in declaration of 'iTCO_vendor_pre_start'
drivers/watchdog/iTCO_vendor_support.c:257: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:258: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:264: error: 'iTCO_vendor_pre_stop' undeclared here (not in a function)
drivers/watchdog/iTCO_vendor_support.c:264: warning: type defaults to 'int' in declaration of 'iTCO_vendor_pre_stop'
drivers/watchdog/iTCO_vendor_support.c:266: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:267: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:273: error: 'iTCO_vendor_pre_keepalive' undeclared here (not in a function)
drivers/watchdog/iTCO_vendor_support.c:273: warning: type defaults to 'int' in declaration of 'iTCO_vendor_pre_keepalive'
drivers/watchdog/iTCO_vendor_support.c:275: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:276: error: expected identifier or '(' before '{' token
drivers/watchdog/iTCO_vendor_support.c:280: error: 'iTCO_vendor_pre_set_heartbeat' undeclared here (not in a function)
drivers/watchdog/iTCO_vendor_support.c:280: warning: type defaults to 'int' in declaration of 'iTCO_vendor_pre_set_heartbeat'
drivers/watchdog/iTCO_vendor_support.c:282:39: error: macro "iTCO_vendor_check_noreboot_on" passed 1 arguments, but takes just 0
drivers/watchdog/iTCO_vendor_support.c:283: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
drivers/watchdog/iTCO_vendor_support.c:291: error: 'iTCO_vendor_check_noreboot_on' undeclared here (not in a function)
drivers/watchdog/iTCO_vendor_support.c:291: warning: type defaults to 'int' in declaration of 'iTCO_vendor_check_noreboot_on'
make[2]: *** [drivers/watchdog/iTCO_vendor_support.o] Error 1
make[1]: *** [drivers/watchdog] Error 2
make: *** [drivers] Error 2

The problem is that iTCO_vendor_support.ko is still being built while
iTCO_vendor.h claims that its functions do not exist. The following
Makefile update fixes that. It causes iTCO_vendor_support.ko to no
longer be built if CONFIG_ITCO_VENDOR_SUPPORT=n.

Signed-off-by: Jean Delvare <khali@linux-fr.org>
Cc: Wim Van Sebroeck <wim@iguana.be>
Signed-off-by: Ingo Molnar <mingo@elte.hu>