scsi: fix build error in fs/compat_ioctl.c
-tip testing found that the build broke in fs/compat_ioctl.c:

----------->
In file included from include/scsi/scsi.h:12,
                 from fs/compat_ioctl.c:72:
include/scsi/scsi_cmnd.h:27:25: warning: "BLK_MAX_CDB" is not defined
include/scsi/scsi_cmnd.h:28:3: error: #error MAX_COMMAND_SIZE can not be bigger than BLK_MAX_CDB
In file included from include/scsi/scsi.h:12,
                 from fs/compat_ioctl.c:72:
include/scsi/scsi_cmnd.h: In function ‘scsi_bidi_cmnd’:
include/scsi/scsi_cmnd.h:182: error: implicit declaration of function ‘blk_bidi_rq’
include/scsi/scsi_cmnd.h:183: error: dereferencing pointer to incomplete type
include/scsi/scsi_cmnd.h: In function ‘scsi_in’:
include/scsi/scsi_cmnd.h:189: error: dereferencing pointer to incomplete type
<-----------

with this config:

  http://redhat.com/~mingo/misc/config-Wed_Jul_16_11_32_32_CEST_2008.bad

I have bisected it down to:

| feac6a07c4a3578bffd6769bb4927e8a7e1f3ffe is first bad commit
| commit feac6a07c4a3578bffd6769bb4927e8a7e1f3ffe
| Author: Martin Petermann <martin@linux.vnet.ibm.com>
| Date:   Wed Jul 2 10:56:35 2008 +0200
|
|    [SCSI] zfcp: Move status accessors from zfcp to SCSI include file.
|
|    Move the accessor functions for the scsi_cmnd status from zfcp to the
|    SCSI include file. Change the interface to the functions to pass the
|    scsi_cmnd pointer instead of the status pointer.
|
|    Signed-off-by: Martin Petermann <martin@linux.vnet.ibm.com>
|    Signed-off-by: Christof Schmitt <christof.schmitt@de.ibm.com>
|    Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>

The problem is due to this aspect of that change:

| @@ -9,6 +9,7 @@
|  #define _SCSI_SCSI_H
|
|  #include <linux/types.h>
| +#include <scsi/scsi_cmnd.h>
|
|  /*
|   * The maximum number of SG segments that we will put inside a

scsi_cmnd.h depends on symbols defined in blkdev.h but those symbols
are not available if !CONFIG_BLOCK.

Only include scsi/scsi_cmnd.h if on CONFIG_BLOCK.
(those methods are not used when CONFIG_BLOCK is off anyway).

Signed-off-by: Ingo Molnar <mingo@elte.hu>