fix 3c515.c:(.text+0x57200): undefined reference to `pnp_get_resource'
-tip testing found the following build failure:

  drivers/built-in.o: In function `corkscrew_setup':
  3c515.c:(.text+0x57200): undefined reference to `pnp_get_resource'

which happens if 3c515.c is build without CONFIG_PNP:

  http://redhat.com/~mingo/misc/config-Fri_Jun_20_10_02_43_CEST_2008.bad

the reason is pnp_irq() use outside of its __ISAPNP__ section.

corkscrew_setup() always called with NULL in the !__ISAPNP__ case, but
also check this condition to make sure.

Signed-off-by: Ingo Molnar <mingo@elte.hu>