Fix net/irda build breakage
commit af0490810cfa159b4894ddecfc5eb2e4432fb976 breaks build for net/irda -

drivers/net/irda/donauboe.c: In function 'toshoboe_interrupt':
drivers/net/irda/donauboe.c:1197: error: 'struct toshoboe_cb' has no member named 'stats'
drivers/net/irda/donauboe.c:1201: error: 'struct toshoboe_cb' has no member named 'stats'
drivers/net/irda/donauboe.c:1283: error: 'struct toshoboe_cb' has no member named 'stats'
make[3]: *** [drivers/net/irda/donauboe.o] Error 1
make[2]: *** [drivers/net/irda] Error 2

Fix this.

Signed-off-by: Parag Warudkar <parag.lkml@gmail.com>
Cc: davem@davemloft.net
Cc: shemminger@vyatta.com
Signed-off-by: Ingo Molnar <mingo@elte.hu>